### ISSUE TITLE
Syntax highlighting fails/stops after "from django.shortcuts import render"

### ISSUE THREAD

**Issue by jedabero** [zacharytamas/atom-django#9]
To reproduce just add

``` python
from django.shortcuts import render
```

at the top, or any other point of a file.
I guess it's because it identifies render as a function so it should have the parenthesis right after it, but I'm pretty sure you cant import a function that way.

**Comment by baxeico** [comment]
Have the same problem: syntax highlighting stops after `from django.template.loader import render_to_string`, see screenshot:

![atom-django-bug](https://cloud.githubusercontent.com/assets/184535/10994119/7ade1962-8474-11e5-91f7-3f75c80700be.png)

**Comment by zacharytamas** [comment]
Working on this now.
